# Generated by Django 3.1.6 on 2021-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210303_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listingDesc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listingStatus',
            field=models.BooleanField(default=True),
        ),
    ]
