# Generated by Django 3.1.6 on 2021-03-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210303_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listingStatus',
            new_name='listingActive',
        ),
    ]
