# Generated by Django 3.1.6 on 2021-03-03 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210303_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listingActive',
            field=models.BooleanField(default=True, verbose_name='Active listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingCategory',
            field=models.CharField(choices=[('fashion', 'fashion'), ('electronics', 'electronics'), ('sports', 'sports'), ('home', 'home'), ('motors', 'motors'), ('art', 'art'), ('business', 'business'), ('media', 'media'), ('others', 'others')], default='others', max_length=64, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingDesc',
            field=models.TextField(blank=True, verbose_name='Item description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingFirstBid',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='Starting bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingImage',
            field=models.URLField(blank=True, verbose_name='Link to image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingName',
            field=models.CharField(max_length=128, verbose_name='Auction item'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingPoster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchedListings', to=settings.AUTH_USER_MODEL, verbose_name='Watchers'),
        ),
    ]
