# Generated by Django 3.1.6 on 2021-03-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210303_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listingCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
