# Generated by Django 3.1.6 on 2021-03-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_listingcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listingFirstBid',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=8, verbose_name='Starting bid'),
        ),
    ]
