# Generated by Django 3.1.6 on 2021-03-10 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_listingwinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listingWinner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listingWinner', to=settings.AUTH_USER_MODEL, verbose_name='Winner'),
        ),
    ]
