# Generated by Django 3.1.6 on 2021-03-10 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210310_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listingWinner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingWinner', to=settings.AUTH_USER_MODEL, verbose_name='Winner'),
        ),
    ]
