# Generated by Django 3.1.6 on 2021-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210310_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listingWinner',
        ),
        migrations.AddField(
            model_name='bid',
            name='haswon',
            field=models.BooleanField(default=False, verbose_name='Auction won by'),
        ),
    ]
