# Generated by Django 3.1.6 on 2021-03-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210310_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='haswon',
            field=models.BooleanField(default=False, verbose_name='Winner bid'),
        ),
    ]
