# Generated by Django 3.1.6 on 2021-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210310_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noOfwatched',
            field=models.IntegerField(default=0, verbose_name='number of listings watched'),
        ),
    ]
